fix: dockercompose

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -4,20 +4,20 @@ FROM golang:1.22 AS builder
 # Устанавливаем рабочую директорию
 WORKDIR /app
 
-# Копируем go.mod и go.sum (если есть) и загружаем зависимости
+# Копируем go.mod и go.sum и загружаем зависимости
 COPY go.mod ./
-RUN go mod download
+RUN go mod tidy
 
-# Копируем все исходники в контейнер
+# Копируем все исходники
 COPY . .
 
-# Собираем приложение
-RUN go build -o /app/app ./cmd
+# Собираем приложение с дополнительными логами для отладки
+RUN go build -o /app/app ./cmd || { echo "Build failed"; exit 1; }
 
 # Финальный образ
 FROM debian:bookworm-slim
 
-# Устанавливаем рабочую директорию
+# Рабочая директория
 WORKDIR /app
 
 # Копируем исполнимый файл из стадии сборки
